#!/bin/bash
#
VERSION=0.4
DIRNAME=`dirname $0`
CONFIG_FILE=${DIRNAME}/Setup.conf
FUNCTIONS_FILE=${DIRNAME}/functions.sh

if [ ! -f $CONFIG_FILE ] ; then
        echo "ERROR: Unable to read $CONFIG_FILE"
        exit 1
fi

. $CONFIG_FILE
. $FUNCTIONS_FILE

check_var
check_linux_bin 

echo Init SSH session host
check_ssh_keyhost cluster1
check_ssh_keyhost cluster2

echo =========================================================================================
echo "cluster1 > $@"
sshpass -p $PASSWD ssh -l admin cluster1 $@ 
echo =========================================================================================
echo "cluster2 > $@"
sshpass -p $PASSWD ssh -l admin cluster2 $@
